[2025-07-15T11:04:42.501+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-15T11:04:42.512+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.ingest_data manual__2025-07-15T10:50:45.194882+00:00 [queued]>
[2025-07-15T11:04:42.517+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.ingest_data manual__2025-07-15T10:50:45.194882+00:00 [queued]>
[2025-07-15T11:04:42.517+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2025-07-15T11:04:42.589+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): ingest_data> on 2025-07-15 10:50:45.194882+00:00
[2025-07-15T11:04:42.592+0000] {standard_task_runner.py:63} INFO - Started process 2919 to run task
[2025-07-15T11:04:42.595+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'ingest_data', 'manual__2025-07-15T10:50:45.194882+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt.py', '--cfg-path', '/tmp/tmpesyarbmg']
[2025-07-15T11:04:42.596+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask ingest_data
[2025-07-15T11:04:42.637+0000] {task_command.py:426} INFO - Running <TaskInstance: run_dbt_models.ingest_data manual__2025-07-15T10:50:45.194882+00:00 [running]> on host ZeeLaptop.localdomain
[2025-07-15T11:04:42.687+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T10:50:45.194882+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T10:50:45.194882+00:00'
[2025-07-15T11:04:42.688+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-15T11:04:42.689+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-15T11:04:42.689+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        /home/reach2zeeshan/clinicaltrials/venv/bin/python /home/reach2zeeshan/clinicaltrials/ingestion/data_ingestion.py\n        ']
[2025-07-15T11:04:42.697+0000] {subprocess.py:86} INFO - Output:
[2025-07-15T11:04:51.892+0000] {subprocess.py:93} INFO - Fetching studies…
[2025-07-15T11:04:51.894+0000] {subprocess.py:93} INFO - Total fetched: 458 records.
[2025-07-15T11:04:51.894+0000] {subprocess.py:93} INFO - Loading into Snowflake…
[2025-07-15T11:04:51.895+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-15T11:04:51.895+0000] {subprocess.py:93} INFO -   File "/home/reach2zeeshan/clinicaltrials/ingestion/data_ingestion.py", line 94, in <module>
[2025-07-15T11:04:51.896+0000] {subprocess.py:93} INFO -     main()
[2025-07-15T11:04:51.896+0000] {subprocess.py:93} INFO -   File "/home/reach2zeeshan/clinicaltrials/ingestion/data_ingestion.py", line 91, in main
[2025-07-15T11:04:51.897+0000] {subprocess.py:93} INFO -     load_to_snowflake(studies)
[2025-07-15T11:04:51.897+0000] {subprocess.py:93} INFO -   File "/home/reach2zeeshan/clinicaltrials/ingestion/data_ingestion.py", line 71, in load_to_snowflake
[2025-07-15T11:04:51.897+0000] {subprocess.py:93} INFO -     success, nchunks, nrows, _ = write_pandas(
[2025-07-15T11:04:51.898+0000] {subprocess.py:93} INFO -                                  ^^^^^^^^^^^^^
[2025-07-15T11:04:51.898+0000] {subprocess.py:93} INFO -   File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/snowflake/connector/pandas_tools.py", line 393, in write_pandas
[2025-07-15T11:04:51.898+0000] {subprocess.py:93} INFO -     isinstance(df.index, pandas.RangeIndex)
[2025-07-15T11:04:51.899+0000] {subprocess.py:93} INFO -                          ^^^^^^^^^^^^^^^^^
[2025-07-15T11:04:51.899+0000] {subprocess.py:93} INFO -   File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/snowflake/connector/options.py", line 36, in __getattr__
[2025-07-15T11:04:51.900+0000] {subprocess.py:93} INFO -     raise errors.MissingDependencyError(self._dep_name)
[2025-07-15T11:04:51.900+0000] {subprocess.py:93} INFO - snowflake.connector.errors.MissingDependencyError: Missing optional dependency: pandas
[2025-07-15T11:04:52.060+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-15T11:04:52.060+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-15T11:04:52.065+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-15T11:04:52.069+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=run_dbt_models, task_id=ingest_data, run_id=manual__2025-07-15T10:50:45.194882+00:00, execution_date=20250715T105045, start_date=20250715T110442, end_date=20250715T110452
[2025-07-15T11:04:52.083+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task ingest_data (Bash command failed. The command returned a non-zero exit code 1.; 2919)
[2025-07-15T11:04:52.113+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-15T11:04:52.125+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-15T11:04:52.132+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
