[2025-07-15T09:51:21.672+0000] {processor.py:161} INFO - Started process (PID=8335) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:51:21.673+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T09:51:21.675+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:51:21.674+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:51:21.678+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:51:21.678+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T09:51:21.678+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:51:21.678+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T09:51:21.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:51:21.692+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-07-15T09:52:13.103+0000] {processor.py:161} INFO - Started process (PID=8430) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:52:13.106+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T09:52:13.108+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:52:13.108+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:52:13.111+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:52:13.111+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T09:52:13.112+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:52:13.112+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T09:52:13.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:52:13.125+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-07-15T09:53:13.653+0000] {processor.py:161} INFO - Started process (PID=8528) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:53:13.657+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T09:53:13.660+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:53:13.658+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:53:13.664+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:53:13.663+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T09:53:13.664+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:53:13.664+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T09:53:13.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:53:13.678+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-07-15T09:54:18.795+0000] {processor.py:161} INFO - Started process (PID=8614) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:54:18.796+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T09:54:18.797+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:54:18.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:54:18.800+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:54:18.800+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T09:54:18.800+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:54:18.800+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T09:54:18.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:54:18.809+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T09:55:19.406+0000] {processor.py:161} INFO - Started process (PID=8701) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:55:19.409+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T09:55:19.411+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:55:19.411+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:55:19.414+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:55:19.414+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T09:55:19.415+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:55:19.415+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T09:55:19.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:55:19.424+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-15T09:56:21.085+0000] {processor.py:161} INFO - Started process (PID=8791) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:56:21.088+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T09:56:21.089+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:56:21.089+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:56:21.092+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:56:21.091+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T09:56:21.092+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:56:21.092+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T09:56:21.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:56:21.101+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T09:57:25.616+0000] {processor.py:161} INFO - Started process (PID=8861) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:57:25.617+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T09:57:25.618+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:57:25.618+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:57:25.621+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:57:25.620+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T09:57:25.622+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:57:25.622+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T09:57:25.622+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:57:25.633+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T09:58:35.661+0000] {processor.py:161} INFO - Started process (PID=8946) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:58:35.665+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T09:58:35.665+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:58:35.665+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:58:35.668+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:58:35.668+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T09:58:35.668+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:58:35.668+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T09:58:35.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:58:35.679+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T09:59:38.206+0000] {processor.py:161} INFO - Started process (PID=9016) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:59:38.209+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T09:59:38.209+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:59:38.209+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:59:38.213+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:59:38.211+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T09:59:38.213+0000] {logging_mixin.py:188} INFO - [2025-07-15T09:59:38.213+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T09:59:38.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T09:59:38.222+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T10:00:38.186+0000] {processor.py:161} INFO - Started process (PID=9081) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:00:38.190+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:00:38.191+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:00:38.191+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:00:38.201+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:00:38.200+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:00:38.202+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:00:38.201+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:00:38.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:00:38.236+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2025-07-15T10:01:38.506+0000] {processor.py:161} INFO - Started process (PID=9175) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:01:38.508+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:01:38.508+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:01:38.508+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:01:38.511+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:01:38.510+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:01:38.511+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:01:38.511+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:01:38.511+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:01:38.521+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-07-15T10:02:41.723+0000] {processor.py:161} INFO - Started process (PID=9291) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:02:41.726+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:02:41.727+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:02:41.726+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:02:41.730+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:02:41.729+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:02:41.730+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:02:41.730+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:02:41.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:02:41.739+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T10:04:16.406+0000] {processor.py:161} INFO - Started process (PID=9397) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:04:16.409+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:04:16.410+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:04:16.409+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:04:16.412+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:04:16.412+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:04:16.413+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:04:16.413+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:04:16.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:04:16.421+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T10:05:18.362+0000] {processor.py:161} INFO - Started process (PID=9465) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:05:18.365+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:05:18.366+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:05:18.366+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:05:18.368+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:05:18.368+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:05:18.369+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:05:18.369+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:05:18.369+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:05:18.377+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T10:06:24.550+0000] {processor.py:161} INFO - Started process (PID=9534) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:06:24.553+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:06:24.554+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:06:24.554+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:06:24.556+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:06:24.556+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:06:24.556+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:06:24.556+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:06:24.557+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:06:24.564+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-07-15T10:07:28.191+0000] {processor.py:161} INFO - Started process (PID=9599) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:07:28.195+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:07:28.196+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:07:28.195+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:07:28.198+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:07:28.198+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:07:28.199+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:07:28.199+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:07:28.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:07:28.208+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T10:08:27.906+0000] {processor.py:161} INFO - Started process (PID=9662) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:08:27.915+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:08:27.916+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:08:27.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:08:27.919+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:08:27.919+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:08:27.919+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:08:27.919+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:08:27.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:08:27.930+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-07-15T10:09:21.217+0000] {processor.py:161} INFO - Started process (PID=9714) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:09:21.220+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:09:21.221+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:09:21.220+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:09:21.225+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:09:21.224+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:09:21.225+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:09:21.225+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:09:21.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:09:21.236+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-15T10:10:53.119+0000] {processor.py:161} INFO - Started process (PID=9813) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:10:53.120+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:10:53.121+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:10:53.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:10:53.124+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:10:53.123+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:10:53.126+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:10:53.126+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:10:53.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:10:53.135+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T10:12:21.672+0000] {processor.py:161} INFO - Started process (PID=9914) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:12:21.675+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:12:21.676+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:12:21.676+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:12:21.680+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:12:21.679+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:12:21.680+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:12:21.680+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:12:21.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:12:21.693+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-07-15T10:13:31.848+0000] {processor.py:161} INFO - Started process (PID=9986) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:13:31.849+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:13:31.849+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:13:31.849+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:13:31.852+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:13:31.852+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:13:31.852+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:13:31.852+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:13:31.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:13:31.861+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T10:14:38.011+0000] {processor.py:161} INFO - Started process (PID=10057) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:14:38.013+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:14:38.014+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:14:38.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:14:38.017+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:14:38.016+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:14:38.018+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:14:38.017+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:14:38.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:14:38.028+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-15T10:15:45.683+0000] {processor.py:161} INFO - Started process (PID=10131) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:15:45.686+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:15:45.687+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:15:45.687+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:15:45.690+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:15:45.689+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:15:45.690+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:15:45.690+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:15:45.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:15:45.699+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T10:16:54.371+0000] {processor.py:161} INFO - Started process (PID=10200) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:16:54.374+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:16:54.375+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:16:54.375+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:16:54.378+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:16:54.378+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:16:54.379+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:16:54.379+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:16:54.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:16:54.391+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-07-15T10:17:59.514+0000] {processor.py:161} INFO - Started process (PID=10288) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:17:59.517+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:17:59.518+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:17:59.518+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:17:59.521+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:17:59.521+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:17:59.521+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:17:59.521+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:17:59.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:17:59.532+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-15T10:19:02.376+0000] {processor.py:161} INFO - Started process (PID=10384) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:19:02.379+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:19:02.380+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:19:02.380+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:19:02.384+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:19:02.383+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:19:02.384+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:19:02.384+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:19:02.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:19:02.397+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-07-15T10:21:10.964+0000] {processor.py:161} INFO - Started process (PID=475) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:21:10.966+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:21:10.967+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:21:10.967+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:21:10.969+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:21:10.969+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:21:10.970+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:21:10.970+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:21:10.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:21:10.978+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-07-15T10:22:19.784+0000] {processor.py:161} INFO - Started process (PID=556) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:22:19.787+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:22:19.789+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:22:19.788+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:22:19.791+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:22:19.791+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:22:19.792+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:22:19.791+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:22:19.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:22:19.802+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-07-15T10:23:23.984+0000] {processor.py:161} INFO - Started process (PID=621) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:23:23.987+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:23:23.989+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:23:23.988+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:23:23.991+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:23:23.991+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:23:23.992+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:23:23.992+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:23:23.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:23:24.000+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T10:24:29.839+0000] {processor.py:161} INFO - Started process (PID=688) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:24:29.842+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:24:29.844+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:24:29.844+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:24:29.847+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:24:29.846+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:24:29.847+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:24:29.847+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:24:29.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:24:29.859+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-07-15T10:25:35.782+0000] {processor.py:161} INFO - Started process (PID=779) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:25:35.784+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:25:35.786+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:25:35.785+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:25:35.789+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:25:35.788+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:25:35.789+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:25:35.789+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:25:35.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:25:35.799+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-15T10:26:58.852+0000] {processor.py:161} INFO - Started process (PID=887) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:26:58.856+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:26:58.857+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:26:58.857+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:26:58.860+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:26:58.859+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:26:58.860+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:26:58.860+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:26:58.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:26:58.869+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T10:27:51.804+0000] {processor.py:161} INFO - Started process (PID=953) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:27:51.807+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:27:51.808+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:27:51.807+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:27:51.810+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:27:51.810+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:27:51.811+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:27:51.811+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:27:51.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:27:51.820+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T10:29:00.912+0000] {processor.py:161} INFO - Started process (PID=1049) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:29:00.915+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:29:00.916+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:29:00.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:29:00.919+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:29:00.918+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:29:00.919+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:29:00.919+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:29:00.919+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:29:00.927+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-07-15T10:31:03.399+0000] {processor.py:161} INFO - Started process (PID=460) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:31:03.403+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:31:03.405+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:31:03.405+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:31:03.411+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:31:03.410+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:31:03.412+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:31:03.411+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:31:03.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:31:03.445+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2025-07-15T10:32:08.328+0000] {processor.py:161} INFO - Started process (PID=546) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:32:08.331+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:32:08.333+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:32:08.332+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:32:08.335+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:32:08.334+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:32:08.335+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:32:08.335+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:32:08.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:32:08.344+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T10:34:56.713+0000] {processor.py:161} INFO - Started process (PID=812) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:34:56.716+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:34:56.717+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:34:56.717+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:34:56.720+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:34:56.719+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:34:56.720+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:34:56.720+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:34:56.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:34:56.728+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-07-15T10:36:02.211+0000] {processor.py:161} INFO - Started process (PID=922) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:36:02.214+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:36:02.216+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:36:02.216+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:36:02.221+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:36:02.219+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:36:02.221+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:36:02.221+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:36:02.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:36:02.238+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-07-15T10:46:15.850+0000] {processor.py:161} INFO - Started process (PID=1417) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:46:15.853+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:46:15.855+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:46:15.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:46:15.858+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:46:15.857+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:46:15.858+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:46:15.858+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:46:15.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:46:15.867+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T10:47:18.693+0000] {processor.py:161} INFO - Started process (PID=1508) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:47:18.697+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:47:18.698+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:47:18.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:47:18.701+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:47:18.701+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:47:18.701+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:47:18.701+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:47:18.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:47:18.709+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-07-15T10:48:21.832+0000] {processor.py:161} INFO - Started process (PID=1574) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:48:21.834+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:48:21.835+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:48:21.835+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:48:21.839+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:48:21.838+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:48:21.840+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:48:21.839+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:48:21.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:48:21.852+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-15T10:49:30.602+0000] {processor.py:161} INFO - Started process (PID=1649) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:49:30.605+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:49:30.607+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:49:30.606+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:49:30.609+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:49:30.609+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:49:30.609+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:49:30.609+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:49:30.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:49:30.618+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-07-15T10:50:32.397+0000] {processor.py:161} INFO - Started process (PID=1727) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:50:32.398+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:50:32.399+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:50:32.399+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:50:32.403+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:50:32.402+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:50:32.403+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:50:32.403+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:50:32.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:50:32.433+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-07-15T10:51:44.063+0000] {processor.py:161} INFO - Started process (PID=1813) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:51:44.066+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:51:44.068+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:51:44.067+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:51:44.071+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:51:44.070+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:51:44.072+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:51:44.072+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:51:44.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:51:44.081+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-15T10:52:51.049+0000] {processor.py:161} INFO - Started process (PID=1882) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:52:51.052+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:52:51.053+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:52:51.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:52:51.056+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:52:51.055+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:52:51.057+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:52:51.056+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:52:51.057+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:52:51.065+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T10:53:53.711+0000] {processor.py:161} INFO - Started process (PID=1952) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:53:53.714+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:53:53.715+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:53:53.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:53:53.718+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:53:53.717+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:53:53.718+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:53:53.718+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:53:53.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:53:53.731+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-15T10:54:56.797+0000] {processor.py:161} INFO - Started process (PID=2029) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:54:56.800+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:54:56.801+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:54:56.801+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:54:56.804+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:54:56.804+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:54:56.805+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:54:56.805+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:54:56.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:54:56.817+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-15T10:55:57.640+0000] {processor.py:161} INFO - Started process (PID=2116) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:55:57.642+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:55:57.642+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:55:57.642+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:55:57.646+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:55:57.645+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:55:57.646+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:55:57.646+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:55:57.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:55:57.655+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-07-15T10:56:49.038+0000] {processor.py:161} INFO - Started process (PID=2182) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:56:49.041+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:56:49.042+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:56:49.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:56:49.047+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:56:49.046+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:56:49.047+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:56:49.047+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:56:49.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:56:49.058+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-07-15T10:57:57.146+0000] {processor.py:161} INFO - Started process (PID=2448) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:57:57.149+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:57:57.150+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:57:57.149+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:57:57.152+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:57:57.152+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:57:57.152+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:57:57.152+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:57:57.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:57:57.163+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-15T10:59:03.002+0000] {processor.py:161} INFO - Started process (PID=2518) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:59:03.006+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T10:59:03.007+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:59:03.007+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:59:03.010+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:59:03.009+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T10:59:03.010+0000] {logging_mixin.py:188} INFO - [2025-07-15T10:59:03.010+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T10:59:03.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T10:59:03.020+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-15T11:00:13.554+0000] {processor.py:161} INFO - Started process (PID=2607) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:00:13.557+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:00:13.558+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:00:13.558+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:00:13.562+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:00:13.561+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:00:13.562+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:00:13.562+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:00:13.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:00:13.570+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-07-15T11:01:19.792+0000] {processor.py:161} INFO - Started process (PID=2675) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:01:19.795+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:01:19.796+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:01:19.796+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:01:19.800+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:01:19.799+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:01:19.801+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:01:19.801+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:01:19.801+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:01:19.814+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-07-15T11:02:28.838+0000] {processor.py:161} INFO - Started process (PID=2755) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:02:28.842+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:02:28.842+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:02:28.842+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:02:28.845+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:02:28.844+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:02:28.845+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:02:28.845+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:02:28.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:02:28.853+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T11:03:48.403+0000] {processor.py:161} INFO - Started process (PID=2858) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:03:48.406+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:03:48.407+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:03:48.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:03:48.410+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:03:48.409+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:03:48.410+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:03:48.410+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:03:48.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:03:48.418+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T11:04:59.808+0000] {processor.py:161} INFO - Started process (PID=2934) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:04:59.811+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:04:59.812+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:04:59.812+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:04:59.815+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:04:59.814+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:04:59.815+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:04:59.815+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:04:59.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:04:59.824+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-15T11:05:54.362+0000] {processor.py:161} INFO - Started process (PID=3028) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:05:54.374+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:05:54.375+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:05:54.375+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:05:54.379+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:05:54.378+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:05:54.379+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:05:54.379+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:05:54.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:05:54.400+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-07-15T11:07:49.495+0000] {processor.py:161} INFO - Started process (PID=3162) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:07:49.498+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:07:49.500+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:07:49.499+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:07:49.503+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:07:49.502+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:07:49.503+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:07:49.503+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:07:49.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:07:49.512+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T11:08:58.222+0000] {processor.py:161} INFO - Started process (PID=3234) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:08:58.226+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:08:58.226+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:08:58.226+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:08:58.229+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:08:58.228+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:08:58.229+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:08:58.229+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:08:58.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:08:58.239+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-15T11:13:42.126+0000] {processor.py:161} INFO - Started process (PID=525) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:13:42.132+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:13:42.134+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:13:42.134+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:13:42.137+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:13:42.137+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:13:42.138+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:13:42.138+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:13:42.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:13:42.151+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-07-15T11:19:49.676+0000] {processor.py:161} INFO - Started process (PID=569) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:19:49.679+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:19:49.681+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:19:49.680+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:19:49.684+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:19:49.683+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:19:49.684+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:19:49.684+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:19:49.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:19:49.695+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-07-15T11:20:42.529+0000] {processor.py:161} INFO - Started process (PID=625) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:20:42.534+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:20:42.535+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:20:42.535+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:20:42.538+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:20:42.538+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:20:42.539+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:20:42.538+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:20:42.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:20:42.547+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-15T11:21:49.459+0000] {processor.py:161} INFO - Started process (PID=698) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:21:49.462+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:21:49.464+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:21:49.463+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:21:49.466+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:21:49.466+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:21:49.467+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:21:49.466+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:21:49.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:21:49.476+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T11:23:01.763+0000] {processor.py:161} INFO - Started process (PID=777) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:23:01.767+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:23:01.769+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:23:01.768+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:23:01.773+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:23:01.772+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:23:01.774+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:23:01.774+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:23:01.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:23:01.790+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-07-15T11:24:07.550+0000] {processor.py:161} INFO - Started process (PID=849) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:24:07.554+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:24:07.556+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:24:07.556+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:24:07.562+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:24:07.562+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:24:07.563+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:24:07.563+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:24:07.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:24:07.577+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-07-15T11:25:24.116+0000] {processor.py:161} INFO - Started process (PID=928) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:25:24.119+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:25:24.121+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:25:24.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:25:24.124+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:25:24.124+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:25:24.124+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:25:24.124+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:25:24.125+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:25:24.134+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T11:26:34.755+0000] {processor.py:161} INFO - Started process (PID=1021) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:26:34.758+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:26:34.760+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:26:34.760+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:26:34.764+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:26:34.763+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:26:34.765+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:26:34.765+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:26:34.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:26:34.775+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-07-15T11:27:45.022+0000] {processor.py:161} INFO - Started process (PID=1781) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:27:45.026+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:27:45.027+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:27:45.027+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:27:45.030+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:27:45.029+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:27:45.030+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:27:45.030+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:27:45.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:27:45.040+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T11:28:50.540+0000] {processor.py:161} INFO - Started process (PID=1852) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:28:50.543+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T11:28:50.544+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:28:50.544+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:28:50.548+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:28:50.547+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T11:28:50.548+0000] {logging_mixin.py:188} INFO - [2025-07-15T11:28:50.548+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T11:28:50.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T11:28:50.557+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-15T12:15:38.108+0000] {processor.py:161} INFO - Started process (PID=1084) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:15:38.112+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T12:15:38.112+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:15:38.112+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:15:38.115+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:15:38.115+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T12:15:38.116+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:15:38.116+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T12:15:38.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:15:38.124+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-07-15T12:16:46.964+0000] {processor.py:161} INFO - Started process (PID=1158) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:16:46.967+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T12:16:46.968+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:16:46.968+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:16:46.971+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:16:46.970+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T12:16:46.971+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:16:46.971+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T12:16:46.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:16:46.978+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-07-15T12:17:49.843+0000] {processor.py:161} INFO - Started process (PID=1232) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:17:49.844+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T12:17:49.845+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:17:49.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:17:49.852+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:17:49.851+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T12:17:49.853+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:17:49.852+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T12:17:49.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:17:49.867+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-07-15T12:19:10.389+0000] {processor.py:161} INFO - Started process (PID=1312) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:19:10.392+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T12:19:10.392+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:19:10.392+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:19:10.396+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:19:10.395+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T12:19:10.397+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:19:10.397+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T12:19:10.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:19:10.406+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-15T12:20:06.124+0000] {processor.py:161} INFO - Started process (PID=1370) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:20:06.127+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T12:20:06.128+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:20:06.128+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:20:06.131+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:20:06.130+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T12:20:06.131+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:20:06.131+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T12:20:06.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:20:06.139+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T12:21:15.005+0000] {processor.py:161} INFO - Started process (PID=1450) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:21:15.009+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T12:21:15.010+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:21:15.009+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:21:15.013+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:21:15.012+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T12:21:15.013+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:21:15.013+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T12:21:15.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:21:15.021+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-15T12:22:24.433+0000] {processor.py:161} INFO - Started process (PID=1524) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:22:24.437+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T12:22:24.438+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:22:24.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:22:24.442+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:22:24.441+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T12:22:24.442+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:22:24.442+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T12:22:24.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:22:24.451+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-07-15T12:23:36.019+0000] {processor.py:161} INFO - Started process (PID=1600) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:23:36.022+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T12:23:36.029+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:23:36.028+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:23:36.034+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:23:36.033+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T12:23:36.034+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:23:36.034+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T12:23:36.034+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:23:36.046+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-07-15T12:24:40.146+0000] {processor.py:161} INFO - Started process (PID=1673) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:24:40.150+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T12:24:40.152+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:24:40.151+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:24:40.158+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:24:40.157+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T12:24:40.158+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:24:40.158+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T12:24:40.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:24:40.174+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-07-15T12:25:48.939+0000] {processor.py:161} INFO - Started process (PID=1748) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:25:48.942+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T12:25:48.947+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:25:48.947+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:25:48.950+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:25:48.950+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T12:25:48.951+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:25:48.950+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T12:25:48.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:25:48.959+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-15T12:26:55.827+0000] {processor.py:161} INFO - Started process (PID=1828) to work on /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:26:55.830+0000] {processor.py:830} INFO - Processing file /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-15T12:26:55.839+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:26:55.838+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:26:55.843+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:26:55.842+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-15T12:26:55.843+0000] {logging_mixin.py:188} INFO - [2025-07-15T12:26:55.843+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-15T12:26:55.843+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-15T12:26:55.852+0000] {processor.py:183} INFO - Processing /home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
